require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DiscountsController do

  def mock_discount(stubs={})
    @mock_discount ||= mock_model(Discount, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all discounts as @discounts" do
      Discount.stub(:all) { [mock_discount] }
      get :index
      assigns(:discounts).should eq([mock_discount])
    end
  end

  describe "GET show" do
    it "assigns the requested discount as @discount" do
      Discount.stub(:find).with("37") { mock_discount }
      get :show, :id => "37"
      assigns(:discount).should be(mock_discount)
    end
  end

  describe "GET new" do
    it "assigns a new discount as @discount" do
      Discount.stub(:new) { mock_discount }
      get :new
      assigns(:discount).should be(mock_discount)
    end
  end

  describe "GET edit" do
    it "assigns the requested discount as @discount" do
      Discount.stub(:find).with("37") { mock_discount }
      get :edit, :id => "37"
      assigns(:discount).should be(mock_discount)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created discount as @discount" do
        Discount.stub(:new).with({'these' => 'params'}) { mock_discount(:save => true) }
        post :create, :discount => {'these' => 'params'}
        assigns(:discount).should be(mock_discount)
      end

      it "redirects to the created discount" do
        Discount.stub(:new) { mock_discount(:save => true) }
        post :create, :discount => {}
        response.should redirect_to(discount_url(mock_discount))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved discount as @discount" do
        Discount.stub(:new).with({'these' => 'params'}) { mock_discount(:save => false) }
        post :create, :discount => {'these' => 'params'}
        assigns(:discount).should be(mock_discount)
      end

      it "re-renders the 'new' template" do
        Discount.stub(:new) { mock_discount(:save => false) }
        post :create, :discount => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested discount" do
        Discount.stub(:find).with("37") { mock_discount }
        mock_discount.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :discount => {'these' => 'params'}
      end

      it "assigns the requested discount as @discount" do
        Discount.stub(:find) { mock_discount(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:discount).should be(mock_discount)
      end

      it "redirects to the discount" do
        Discount.stub(:find) { mock_discount(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(discount_url(mock_discount))
      end
    end

    describe "with invalid params" do
      it "assigns the discount as @discount" do
        Discount.stub(:find) { mock_discount(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:discount).should be(mock_discount)
      end

      it "re-renders the 'edit' template" do
        Discount.stub(:find) { mock_discount(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested discount" do
      Discount.stub(:find).with("37") { mock_discount }
      mock_discount.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the discounts list" do
      Discount.stub(:find) { mock_discount }
      delete :destroy, :id => "1"
      response.should redirect_to(discounts_url)
    end
  end

end
